### ISSUE TITLE
Multithreading issue

### ISSUE THREAD

**Issue by demglobekkeper** [massoudss/waveformSeekBar#15]
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.example.chat/files/Documents/amplituda_tmp_values.txt (No such file or directory)

Guys, there is a problem that a library doesn't work when you start **getSampleFrom**. Is it possible to fix it somehow? 
It works for a single file. But with multiple files it doesn't((

```
WaveformOptions.getSampleFrom(file.path) {
                    waves = it
                }
```

**Comment by lincollincol** [comment]
Hello @demglobekkeper, thank you for reporting this bug. I'll try to fix it as soon as possible!
