### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by alhajsid** [massoudss/waveformSeekBar#18]
when setting setSampleFrom
`seekBarprogress.setSampleFrom(MyService.currentplaingsong!!.aPath)`

it giving `java.lang.NumberFormatException: For input string: ""`

aPath is "/storage/emulated/0/Music temp/# 0 Nazar Lag Jayegi - Millind Gaba 320Kbps.mp3"

**Comment by lincollincol** [comment]
@alhajsid I'd like to process your audio file on my computer. Can you share it with me as an attached file?
