### ISSUE TITLE
Not Supported File Extension

### ISSUE THREAD

**Issue by xeinebiu** [massoudss/waveformSeekBar#2]
Please allow the "setSampleFrom" to accept file path without extension.

I have some audio files without extension that are available only on my App.

**Comment by massoudss** [comment]
OK, I will work on it.

**Comment by xeinebiu** [comment]
> OK, I will work on it.

Thank you. :)

**Comment by massoudss** [comment]
Version 1.1.2 released.

Use these methods to customize file extensions:
```
addCustomExtension(extension: String)
removeCustomExtension(extension: String)
addCustomExtensions(extensions: List<String>)
removeCustomExtensions(extensions: List<String>)
```
Or ignore:
```
setSampleFrom(file: File, ignoreExtension: Boolean)
setSampleFrom(path: String, ignoreExtension: Boolean)
```

**Comment by xeinebiu** [comment]
> Version 1.1.2 released.
> 
> Use these methods to customize file extensions:
> 
> ```
> addCustomExtension(extension: String)
> removeCustomExtension(extension: String)
> addCustomExtensions(extensions: List<String>)
> removeCustomExtensions(extensions: List<String>)
> ```
> 
> Or ignore:
> 
> ```
> setSampleFrom(file: File, ignoreExtension: Boolean)
> setSampleFrom(path: String, ignoreExtension: Boolean)
> ```

great work @massoudss 
Thank you.
