### ISSUE TITLE
Extract Amplituda library from WaveformSeekbar

### ISSUE THREAD

**Issue by lincollincol** [massoudss/waveformSeekBar#21]
- User should be able to use their own sample data
- WaveformSeekbar library should not depend on changes in Amplituda library
- It will reduce library size

**Comment by PBasil2020** [comment]
I am included activity_main.xml library in my dependency, still the problem persists

**Comment by PBasil2020** [comment]
Included the Amplituda dependency, but problem persists

**Comment by lincollincol** [comment]
@PBasil2020 Hello. This does not apply to WavefromSeekbar library, so you should open a new issue here -> https://github.com/lincollincol/Amplituda
