### ISSUE TITLE
Just several suggestions

### ISSUE THREAD

**Issue by achatina** [massoudss/waveformSeekBar#23]
Hi there! Tried your library and met with a couple of things.
1. MaxProgress in Float, but Progress in integer. Due to how you use it, they both should be Float.
2. Don't throw Exception if there is no data. Just don't draw. Why? Take a look at my case. I'm using Constraint Layout root layout for RV items. Firstly I'm showing the screen data with some kind of progress and then set some data. But when it creates a view holder, it crashes, as I don't have any data by now. So there are 2 options for me: play with visibility, but as soon as I have a skeleton for progress, it makes some difficulties. The second option is to set some kind of default data, like intArrayOf(1). Both variants are not so good.
3. Change progress by tap, not by swipe. For changing progress I need to swipe on this view, but it is not very comfortable. It will be better to add logic for seeking by a single tap.

**Comment by lincollincol** [comment]
@achatina Hello,
1. @massoudss or @yoadey 
2. I'll fix it soon. 
3. I can't reproduce this bug, you made a mistake somewhere. This may be due to the height of the widget.

**Comment by achatina** [comment]
And one more point for future improvements. Not ignoring lint notification by @SuppressLint("DrawAllocation") :)
You can create proper classes not in draw method, but in onSizeChanged callback. As it is a progress view that can be updated each 50-100ms it is really difficult thing of creating Bitmap each time

**Comment by achatina** [comment]
Also, this can be achieved by `onProgressChanged?.onProgressChanged`
so it will be more Kotlin-style and a little bit safier as if() is not atomic. (there are a lot of places like this)

https://github.com/massoudss/waveformSeekBar/blob/83402c21fb76db30d5675621cea14d472ccd790a/lib/src/main/java/com/masoudss/lib/WaveformSeekBar.kt#L212-L213

**Comment by achatina** [comment]
Sorry for this kind of "code review" from noname, but as I really liked this lib and took it in my project just can't be staying aside :)

**Comment by massoudss** [comment]
Hi All, thanks for your contributions.
@yoadey, in my opinion fixing the incompatibility with previous versions is easy and can be ignored.
I will change it to float.

**Comment by massoudss** [comment]
@achatina I'm working on it, thanks.
