### ISSUE TITLE
Upload file from url

### ISSUE THREAD

**Issue by AleAmla987** [massoudss/waveformSeekBar#26]
Hello! How can I load a file from a url and thus implement the layout?
That integer array what does it have to refer to? what should i add? affects the design only or refers to the duration of the audio
waveform SeekBar.set Sample From (samples: Int Array) // or Java array => new int [] {/ * samples * /}
I send you a hug from Argentina

**Comment by massoudss** [comment]
Hi
You have to download your file first and generate sample array from saved audio file.
If you want show waveform without downloading the file, you should precompute sample array and save it on server side.
