### ISSUE TITLE
a wave form sample of zeroes causes the WaveFormSeekbar to not be Rendered.

### ISSUE THREAD

**Issue by anasmadrhar** [massoudss/waveformSeekBar#28]
Hello,
Using an intArray of zeroes will cause the seekbar to be invisible or not rendered 
` waveFormSeekbar.setSampleFrom(intArrayOf(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))`
this is probably because of MaxValue being 0 which leads to a NaN in the waveHeight variable inside onDraw.

**Comment by massoudss** [comment]
Hi
Please update the `waveformSeekBar` to **3.1.0** & the `Amplituda` to **2.1.0**.
