### ISSUE TITLE
Bug: WaveGravity maps to wrong values

### ISSUE THREAD

**Issue by yoadey** [massoudss/waveformSeekBar#34]
Since the last update, when I select waveGravity=center, the waves are drawn instead at the bottom.

Cause:
The WaveGravity maps to the wrong values: top -> 1, center to 2 and bottom -> 3, but the enum from where the codes are mapped starts with 0, so it should be top -> 0, center to 1 and bottom -> 2 or the enum definition must be changed.

**Comment by massoudss** [comment]
This issue is now fixed on 4.0.1 version.
Thanks.
