### ISSUE TITLE
is amr file not supported?

### ISSUE THREAD

**Issue by pmrzygweb** [massoudss/waveformSeekBar#35]
I tried amr file as a source but it crashes the app. what format audio files are supported?

**Comment by massoudss** [comment]
Hi
What is your crash log?

**Comment by pmrzygweb** [comment]
`Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 22864 (ssageforandroid)`
@massoudss This error shows in logcat

**Comment by massoudss** [comment]
This issue is related to [Amplituda library](https://github.com/lincollincol/Amplituda).

**Comment by lincollincol** [comment]
@pmrzygweb Please update Amplituda to 2.1.2
`implementation 'com.github.lincollincol:amplituda:2.1.2'`

**Comment by pmrzygweb** [comment]
awesome, it works like a charm, thanks @lincollincol
