### ISSUE TITLE
Sample Generator without Rendering

### ISSUE THREAD

**Issue by xeinebiu** [massoudss/waveformSeekBar#4]
Hi.

1.1.3 works like a charm, except that Generating the Sample takes some seconds.

For the current Version, we can retrieve the Generated Sample Data via the setSampleFrom(arg, arg) method.

Can you please make a method which only Returns the Generated sample without rendering.

The idea is to generate on background all the Sample data's  for each audio file
and then use the results for Rendering.

Thank You.

**Comment by massoudss** [comment]
You can use `WaveformOptions.getSampleFrom(file, ignoreExtension): IntArray` to preload samples.
