### ISSUE TITLE
Need support for other formats like .3gp, mp4 etc

### ISSUE THREAD

**Issue by mohsin-ali-brainx** [massoudss/waveformSeekBar#47]
I have a feature where I have to record an audio using Mic which is implemented by using MediaRecorder and it only output file format for .3gp as there is no encoder for .mp3 file to we have to specify the output format in .3gp.
so when passed this file path it does not create the amplitude and seekbar for it. I'm using this library with amplitude library in Android.

**Comment by massoudss** [comment]
You can use FFMpeg to convert mp4, 3gp files to supported formats like mp3.
Dear @lincollincol is it possible to support mp4 and 3gp formats in amplitude library?
