### ISSUE TITLE
No drawed when amplitude result return int array contains only 0

### ISSUE THREAD

**Issue by Bolid** [massoudss/waveformSeekBar#49]
I did the analysis and realized that if the ampiluda that you use to get the array returns an array of zeros, then nothing will be drawn.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/3057765/195283574-4e7fb048-1620-4b20-b2d5-250d2cbe5c5c.png">

Divide by zero

**Comment by massoudss** [comment]
This is issue is fixed on v5.0.2
