### ISSUE TITLE
compressing sample

### ISSUE THREAD

**Issue by mrezasaeidi** [massoudss/waveformSeekBar#5]
hi
it is good to add some parameter to compress sample result (Int Array) and scale to specific size of array or get max value for frameGain and scale result from 0 to max.
for example chunk samples and return avg of them for one frameGain
or skip some of them to reach the specific parameter better speed and lower size (sending JSON).

**Comment by massoudss** [comment]
Starting from v2.0.0, extracting samples is much faster than before.
Compressing sample for saving into local database or remote server can be done outside of library.
