### ISSUE TITLE
How to link waveform with audio 

### ISSUE THREAD

**Issue by timplifier** [massoudss/waveformSeekBar#51]

**Comment by massoudss** [comment]
You can set sample using described methods. [See Link](https://github.com/massoudss/waveformSeekBar#set-samples).

**Comment by timplifier** [comment]
I mean, when audio is playing changing the waveform progress

**Comment by massoudss** [comment]
So you have to change wavefrom progress as soon as your audio is playing.
For example if your audio is 100 seconds you should change progress from 0 to 100 every second.

> wavefrom.progress = 0f to 100f

If you want a smooth progress, progress value should be updated in sooner intervals e.g. every 100 ms.
