### ISSUE TITLE
App crashed when notifydatasetChanged is called() 

### ISSUE THREAD

**Issue by Usama99786** [massoudss/waveformSeekBar#52]
I am building a chat module. So whenever I send an audio in the chat and the recyclerview adapter is refreshed, It crashes on
                                    mBinding?.waveform?.setSampleFrom(file_path)
in the adapter. It also crashes randomly sometimes when there are a lot of audio messages as well. It gives the following exception
W/System.err: linc.com.amplituda.exceptions.processing.PacketSubmittingException: Error submitting a packet for decoding!
I would really appreciate some help here.

**Comment by massoudss** [comment]
It seems this crash comes from Amplitude library, better to open another issue [here](https://github.com/lincollincol/Amplituda/issues).
@lincollincol
