### ISSUE TITLE
When wave is creating it is taking too much time

### ISSUE THREAD

**Issue by Karikw3** [massoudss/waveformSeekBar#6]
When wave is creating it is taking too much time as i am using song which is of not more size .
If you can tell me about this .please let me know

**Comment by xeinebiu** [comment]
#You need to cache the Wave's and next time, instead of passing the song as argument, you pass the cached result.

**Comment by Karikw3** [comment]
@xeinebiu here i have to use a song link  which is coming from server in format of mp3.

**Comment by xeinebiu** [comment]
> @xeinebiu here i have to use a song link which is coming from server in format of mp3.

I dont think that really matters where you get the Song from. But lets follow an online song example.

1. Get the song Url
2. Based on the url, check if you have any wave data calculated before. If no, follow step 3. If yes, follow step 5.
3. Calculate Wave Data
4. Save the result locally.
5. Display the result.

**Comment by Karikw3** [comment]
Ohh ...
Thank you so much for this ....
But can you have a code example  for this where i can check this it will be a great help for me as i ams earching this solution from 2 months .

**Comment by animsh** [comment]
@Karikw3 did you got success in calculating wave data of song? If yes can you you please share it?
or @xeinebiu @massoudss can you please help to calculate wave data of song into array? I am searching for it but didn't got answer anywhere
