### ISSUE TITLE
work with Java

### ISSUE THREAD

**Issue by ILanRaz** [massoudss/waveformSeekBar#7]
Hi

I know how work with seekbar but it isnt work with wavebar

on java its :

seekBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
              ){

How make it work?
Can you help please?

**Comment by jhavishal10** [comment]
did you tried this ???

``` private val mySeekbarChangeListener = object : SeekBar.OnSeekBarChangeListener {
            override fun onProgressChanged(seekBar: SeekBar?, progress: Int, fromUser: Boolean) {
               //do something
            }

            override fun onStartTrackingTouch(seekBar: SeekBar?) {
            }

            override fun onStopTrackingTouch(seekBar: SeekBar?) {
                //do something
            }
        }
```

```mySeekBar.setOnSeekBarChangeListener(mySeekbarChangeListener)```

**Comment by ILanRaz** [comment]
now its work
thanks

**Comment by jhavishal10** [comment]
what was the issue ?

**Comment by ILanRaz** [comment]
I just coded in wrong way 
on java Its work like this :
 waveformSeekBar.setOnProgressChanged(new SeekBarOnProgressChanged() {
            @Override
            public void onProgressChanged(@NotNull WaveformSeekBar waveformSeekBar, int progress, boolean fromUser) {
                if (fromUser){
                    mediaPlayer.seekTo(progress);
                    waveformSeekBar.setProgress(progress);
                }

            }

Many thanks!
